# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75be81bc3be6e8e479ff792e42ce2a2d2c4378cd2ae1f8e7a2f80e7169fed79c03e21f5db6027946eac11a96363b5f7faee61d032eefc7332649c4aa75728d8

test:
  secret_key_base: 3d50c4734dca247f44ad6b6aa0e6f5b6faab3100a19db9b70f11fcafcdaf81b16964004f287d8f7bae6ca65792a2cdd8a702dc9d5001a9c06e38c7958630eafa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
